cc_test(
    name = "test_hdlib",
    size = "small",
    srcs = [
        "test_ordered_vector.cpp",
        "test_small_vector.cpp",
        "test_static_vector.cpp",
        "test_string_utils.cpp",
    ],
    deps = [
        "//:hdlib",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "test_algorithm",
    size = "small",
    srcs = [
        "test_algorithm.cpp",
    ],
    deps = [
        "//:hdlib",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "test_string_utils",
    size = "small",
    srcs = [
        "test_string_utils.cpp",
    ],
    deps = [
        "//:hdlib",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "test_channel",
    size = "small",
    srcs = [
        "test_channel.cpp",
    ],
    deps = [
        "//:hdlib",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "test_bitset",
    size = "small",
    srcs = [
        "test_bitset.cpp",
    ],
    deps = [
        "//:hdlib",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "test_hash",
    size = "small",
    srcs = [
        "test_hash.cpp",
    ],
    deps = [
        "//:hdlib",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "test_bloom",
    size = "small",
    srcs = [
        "test_bloom.cpp",
    ],
    deps = [
        "//:hdlib",
        "@googletest//:gtest_main",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "test_timeit",
    srcs = [
        "test_timeit.cpp",
    ],
    deps = [
        "//:hdlib",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "test_lifetime",
    srcs = [
        "test_lifetime.cpp",
    ],
    deps = [
        "//:hdlib",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "test_defer",
    srcs = [
        "test_defer.cpp",
    ],
    deps = [
        "//:hdlib",
    ],
    visibility = ["//visibility:public"],
)
